spring:
  data:
    mongodb:
      host: localhost
      username: nongtrai
      password: P@ssword123
      database: nongtrai
      port: 27017
  http:
    multipart:
      location: E:\nongtraidemo\uploaded\
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB